// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2XISrElQqzjd8pz_1mO-WtGWUldEPaw',
    appId: '1:672483596043:web:b207e7f3a083f2c14fb40e',
    messagingSenderId: '672483596043',
    projectId: 'opetlocator',
    authDomain: 'opetlocator.firebaseapp.com',
    storageBucket: 'opetlocator.appspot.com',
    measurementId: 'G-MCQD0HE8Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQKs2fcBAhpBVB56XR6nMVa0QO3c80pQ',
    appId: '1:672483596043:android:c764d9ca41562b5b4fb40e',
    messagingSenderId: '672483596043',
    projectId: 'opetlocator',
    storageBucket: 'opetlocator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-aaVSURZy2iNG1dfDD5FpTM9_-T27QWY',
    appId: '1:672483596043:ios:144f8017b63f6b3b4fb40e',
    messagingSenderId: '672483596043',
    projectId: 'opetlocator',
    storageBucket: 'opetlocator.appspot.com',
    iosBundleId: 'com.example.opetStationLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-aaVSURZy2iNG1dfDD5FpTM9_-T27QWY',
    appId: '1:672483596043:ios:144f8017b63f6b3b4fb40e',
    messagingSenderId: '672483596043',
    projectId: 'opetlocator',
    storageBucket: 'opetlocator.appspot.com',
    iosBundleId: 'com.example.opetStationLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2XISrElQqzjd8pz_1mO-WtGWUldEPaw',
    appId: '1:672483596043:web:d34822fdff98aa044fb40e',
    messagingSenderId: '672483596043',
    projectId: 'opetlocator',
    authDomain: 'opetlocator.firebaseapp.com',
    storageBucket: 'opetlocator.appspot.com',
    measurementId: 'G-4Z5B3HE56K',
  );
}
